#!/usr/bin/env bash

TEST="npm test"


eval MACHINE=pc BITS=32 $TEST || exit 1
eval MACHINE=pc BITS=64 $TEST || exit 2
eval MACHINE=raspi2     $TEST || exit 3


#
# Upload release to GitHub
#

if [ "$BRANCH_NAME" = "master" && "$NPM_TOKEN" ]; then
  ci-publish
fi
