#!/usr/bin/env node

var manager = require('download-manager')


// Source versions

const LINUX_VERSION = require('../package.json').version


// Source URLs

const LINUX_URL = "https://www.kernel.org/pub/linux/kernel/v4.x/linux-"+LINUX_VERSION+".tar.gz"


// Checksums

const LINUX_SHA256 = 'e0f94919c6f387db166e106a02b7a3887d1bd051eb2f75e218c456545a64b7c9'


// Patch Linux kernel to add Unicode BMP support on `fbcon`
const LINUX_CJKTTY_VERSION = "4.12"
const LINUX_CJKTTY_PATCH = "https://raw.githubusercontent.com/NodeOS/cjktty-patch/master/patches/linux-"+LINUX_CJKTTY_VERSION+"-cjktty.diff"


//
// Node.js
//

var downloads =
[
  {
    name: 'linux',
    url: LINUX_URL,
    sha256: LINUX_SHA256,
    patch:
    [
      {
        url: LINUX_CJKTTY_PATCH,
        strip: 1
      },
      {
        url: 'resources/linux-vagrant.patch',
        strip: 1
      },
      {
        url: 'resources/logo.patch',
        strip: 1
      }
    ]
  }
]


manager(downloads, {path: 'deps'}, function(error)
{
  if(error)
  {
    console.trace(error)
    process.exit(1)
  }
})
